# Service ??
server:
  port: 9091
  servlet:
    context-path: /api


---
# Log Level ??
logging:
  level:
    root: debug


---
# ActiveMQ ?? ??
activemq:
  user: pan_admin
  password: dkpan@#2023!$
  openwire:
    protocol: ssl
    url: b-f142d8f9-4d6e-4736-9a78-1bf6cd395c86-1.mq.ap-northeast-2.amazonaws.com
    port: 61617
  stomp:
    protocol: stomp+ssl
    url: b-f142d8f9-4d6e-4736-9a78-1bf6cd395c86-1.mq.ap-northeast-2.amazonaws.com
    port: 61614
